version: '3.3'
services:
    testcafeA:
        volumes:
            - 'C:\Users\lalit.sharma\AppData\Roaming\npm\node_modules:/node_modules'
        image: testdockerlalit/testcafe
        stdin_open: true
        tty: true
        entrypoint: sh -c '${SCRIPT1}'